# Generated by Django 3.2.25 on 2025-01-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_table',
            name='slot',
        ),
    ]
