# Generated by Django 3.2.25 on 2025-04-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_booking_table_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_table',
            name='report_typr',
            field=models.CharField(max_length=200),
        ),
    ]
